### ISSUE TITLE
Tests fail on ARMv7

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#507]
## Expected Behaviour

Unit tests to pass in an unmodified Dockerfile

## Current Behaviour

```
Step 8/14 : RUN go test $(go list ./... | grep -v /vendor/ | grep -v /template/|grep -v /build/) -cover  && VERSION=$(git describe --all --exact-match `git rev-parse HEAD` | grep tags | sed 's/tags\///')  && GIT_COMMIT=$(git rev-list -1 HEAD)  && CGO_ENABLED=0 GOOS=linux go build --ldflags "-s -w     -X github.com/openfaas/faas-cli/version.GitCommit=${GIT_COMMIT}     -X github.com/openfaas/faas-cli/version.Version=${VERSION}"     -a -installsuffix cgo -o faas-cli
 ---> Running in ea66de533a10
# github.com/openfaas/faas-cli/proxy
unexpected fault address 0x10044030
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10044030 pc=0x1c4a88]

goroutine 1 [running]:
runtime.throw(0x6a5809, 0x5)
	/usr/local/go/src/runtime/panic.go:605 +0x70 fp=0x120a0830 sp=0x120a0824 pc=0x3b3bc
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x1cc fp=0x120a0854 sp=0x120a0830 pc=0x4ea30
cmd/compile/internal/types.(*Type).IsMemory(...)
	/usr/local/go/src/cmd/compile/internal/types/type.go:1328
cmd/compile/internal/ssa.dse(0x11d6f4a0)
	/usr/local/go/src/cmd/compile/internal/ssa/deadstore.go:35 +0x73c fp=0x120a0960 sp=0x120a0858 pc=0x1c4a88
cmd/compile/internal/ssa.Compile(0x11d6f4a0)
	/usr/local/go/src/cmd/compile/internal/ssa/compile.go:70 +0x27c fp=0x120a3ad4 sp=0x120a0960 pc=0x1bb188
cmd/compile/internal/gc.buildssa(0x116641a0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:216 +0xc3c fp=0x120a3b90 sp=0x120a3ad4 pc=0x5826ec
cmd/compile/internal/gc.compileSSA(0x116641a0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:240 +0x24 fp=0x120a3bd0 sp=0x120a3b90 pc=0x556568
cmd/compile/internal/gc.compile(0x116641a0)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:219 +0x20c fp=0x120a3c00 sp=0x120a3bd0 pc=0x556498
cmd/compile/internal/gc.funccompile(0x116641a0)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1049 +0xa4 fp=0x120a3c28 sp=0x120a3c00 pc=0x50bf98
cmd/compile/internal/gc.Main(0x6c6010)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:585 +0x27e4 fp=0x120a3f80 sp=0x120a3c28 pc=0x536748
main.main()
	/usr/local/go/src/cmd/compile/main.go:49 +0x7c fp=0x120a3fb8 sp=0x120a3f80 pc=0x633134
runtime.main()
	/usr/local/go/src/runtime/proc.go:195 +0x21c fp=0x120a3fe4 sp=0x120a3fb8 pc=0x3c990
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:971 +0x4 fp=0x120a3fe4 sp=0x120a3fe4 pc=0x65374
```

## Possible Solution

Try bumping Golang version.

## Steps to Reproduce (for bugs)

1. Use an ARMv7 machine such as RP2/3/3B+ or Scaleway ARMv7 VM
2. Run `make ci-armhf`

## Context

We generally don't build the `faas-cli` for ARM due to the multi-arch binary build in build_redist.sh, but in this example we could use a Docker image which contains the faas-cli and which works on ARM.

```
cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"


Linux cm3a 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux
```

**Comment by alexellis** [comment]
I've since restarted the machine and pushed `openfaas/faas-cli:0.7.0-armhf`

**Comment by alexellis** [comment]
Derek add label: revisit
